### ISSUE TITLE
[feature] add glyph selection to fontEdit

### ISSUE THREAD

**Issue by JoeStrout** [JoeStrout/minimicro-fonts#1]
The fontEdit.ms program (in the util folder) can load a BMF font, and list all the glyphs in that font in a scrolling list between the color palette and the paint area.
![image](https://user-images.githubusercontent.com/263365/189789123-56a2f9cf-a6c1-496d-8c35-15703ec00566.png)

However, the paint area currently always shows the glyph for "F"; clicking in the glyph list does nothing.  The objective of this issue is to **enable clicking in the glyph list, to select the currently displayed glyph**.  Possible steps:

1. The current tab (`selectedTab`) already has a `font` property; give it a `curChar` property, which is the character we are currently editing.
2. In the `glyphList.draw` method, draw a steely blue background to the selected row.
3. In `glyphList.checkEvents`, check for a mouse-down in self, and work out which row was hit.  Change `selectedTab.curChar`; then change `selectedTab.image` to the image of that char.
4. Finally, update everything related to the currently-being-edited image, using the sort of code that `OpenFile.loadToEditArea` does.  In fact maybe you can just call that (the selected tab is a subclass of `OpenFile`).

When done, we should be able to scroll through the glyph list, click on any glyph, and see a big view of that glyph in the editing area.

**Comment by JoeStrout** [comment]
Ooh, for bonus points: before you clobber the current contents of `fatbits`, grab it and assign it to the `image` property of the charData for that font (i.e. `selectedTab.font.charData(selectedTab.curChar).image`).  That is where the image for each glyph is stored, so if you do this, then we should be able to edit a glyph, switch to some other glyph, switch back, and see our edits still intact.

**Comment by dwaynewilliam** [comment]
If you do this, we should be able to change a glyph because that is where the image for each one is saved.

**Comment by JoeStrout** [comment]
That's correct.  The actual editing (changing the glyph pixels) is already implemented.  So this feature (and the [bounty](https://app.bountysource.com/issues/111282532-feature-add-glyph-selection-to-fontedit)!) is just to make it so you can switch which glyph you're editing.

**Comment by JoeStrout** [comment]
Tested and verified.  Nice work!
